### -------------- Status Checks ---------------------------
GET http://localhost:3000/api/aslkdfj
###
GET http://localhost:3000/api
###
GET http://localhost:3000/api/db

### ------------------ Signup ---------------------------

POST http://localhost:3000/api/user/signup
content-type: application/json

{
"username": "JohnSnow", "email": "idontwantit@castleblack.com", "password": "Daenerys123"
}

### ----------------- Login ----------------------------------------

POST http://localhost:3000/api/user/login
content-type: application/json

{
"username": "JohnSnow",  "password": "Daenerys123"
}

#### ---------------------- rooms -------------------------------------

GET http://localhost:3000/api/rooms?namespace=/

###

POST http://localhost:3000/api/rooms/private
content-type: application/json

{
"passcode": "YaXA9tes", "userId": "65f6cc24eeb0ca5320c42704", "roomName": "privateRoom"
}

###

GET http://localhost:3000/api/rooms/private?userId=65f6cc24eeb0ca5320c42704
