### -------------- Status Checks ---------------------------
GET http://localhost:3000/api/aslkdfj
###
GET http://localhost:3000/api
###
GET http://localhost:3000/api/db

### ------------------ Signup ---------------------------

POST http://localhost:3000/api/user/signup
content-type: application/json

{
"username": "JohnSnow", "email": "idontwantit@castleblack.com", "password": "Daenerys123"
}

### ----------------- Login ----------------------------------------

POST http://localhost:3000/api/user/login
content-type: application/json

{
"username": "JohnSnow",  "password": "Daenerys123"
}
